language: elixir
elixir:
  - 1.6.5
  - 1.7.3
otp_release:
  - 20.3
  - 21.0
script:
  - mix format --check-formatted
  - mix credo list --format=oneline --strict
  - MIX_ENV=prod mix do compile --warnings-as-errors --force
  - mix dialyzer --halt-exit-status
  - MIX_ENV=test mix coveralls.json
cache:
  directories:
    - _build
    - deps
branches:
  only:
    - master
after_success:
  - bash <(curl -s https://codecov.io/bash)
