name: Elixir CI

on: push

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.10.3, 1.11.0]
        otp: [22.3, 23.1]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: mix deps.get
    - name: Compile dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: mix deps.compile
    - name: Check formatted
      run: mix format --check-formatted
    - name: Check unused dependencies
      run: mix deps.unlock --check-unused
    - name: Credo
      run: mix credo --strict --format oneline
    - name: Restore Dialyzer PLT cache
      uses: actions/cache@v2
      with:
        path: /priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plt
    - name: Dialyzer
      run: mix dialyzer
    - name: Run tests
      run: mix test
