name: Elixir CI

on: push

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.10.3, 1.11.0]
        otp: [22.3, 23.1]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      id: deps-cache
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix
    - name: Install dependencies
      run: mix deps.get
    - name: Compile dependencies
      run: mix deps.compile
    - name: Format
      run: mix format --check-formatted
    - name: Compile
      run: mix compile --warnings-as-errors
    - name: Unused dependencies
      run: mix deps.unlock --check-unused
    - name: Lint
      run: mix credo --strict --format oneline
    - name: Restore Dialyzer PLT cache
      uses: actions/cache@v2
      id: plt-cache
      with:
        path: /priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plt-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plt
    - name: Dialyzer
      run: mix dialyzer --halt-exit-status
    - name: Tests
      run: mix test
